### ISSUE TITLE
获取不到正确路径

### ISSUE THREAD

**Issue by 502milk** [ltxhhz/where-is-my-file#1]
![Screenshot_2024-04-06-06-21-29-083_com.ltxhhz.where_is_my_file.jpg](https://github.com/ltxhhz/where-is-my-file/assets/49502047/dd7cfa82-d42e-4cde-a6d2-40c86e3f474c)

应用版本1.1
微信8.0.48
安卓13

**Comment by ltxhhz** [comment]
因为这种 Content Provider 提供的 uri 一般是获取不到真实路径的，所以路径那一栏是 “**可能的路径**”
如果你有其他的实现方法也可以提供一下
